### ISSUE TITLE
Request for settings option to change default token format

### ISSUE THREAD

**Issue by PurdueGuy531** [rfennell/ParametersXmlAddin#8]
Not an issue but a simple feature request. In VS under Tools/Options menu and then 'Parameters XML Addin', could you please add an option to change the pre and post tag/token characters? You currently default to double underscore. It would be immensely handy to change these since I use the popular "Replace Tokens" TFS task from Guillaume Rochon (found in TFS marketplace) - which defaults to "#{" and "}#".

Thanks for your consideration!
Chris

**Comment by rfennell** [comment]
I see your point, I use that task too. 

The issue is the delimiter is set (and all the work is done) using a set of XSLT transform files, the one used depends on the options chosen. I need to come up with a way of swapping the delimiter in the template file prior to it being used.

I will have an experiment

**Comment by rfennell** [comment]
OK had a quick look at the code, the issue is that the XSLT is stored as an embedded resource. The resource loader streams the contents straight into XslCompiledTransform. I am struggling to intercept the file/resource contents, which I would need to do swap the delimiter.

I had thought I could get at it as a string at some point, but the code is too neat and the XslCompiledTransform.Load does not take a simple string.

Needs more thought

**Comment by rfennell** [comment]
Worked out how to do it, release in version 1.6
